//! Sensitive clipboard filtering, per [nspasteboard.org](https://nspasteboard.org/)
//! (re-read 2026-10-06; page last updated 2026-05-30).
//!
//! Skipped entirely, never stored:
//!
//! - **concealed**: `org.nspasteboard.ConcealedType`, and 1Password's legacy
//!   `com.agilebits.onepassword`
//! - **transient**: `org.nspasteboard.TransientType`, and the legacy markers
//!   `de.petermaurer.TransientPasteboardType` (TextExpander, Butler),
//!   `com.typeit4me.clipping` (TypeIt4Me), `Pasteboard generator type` (Typinator)
//! - **auto-generated**: `org.nspasteboard.AutoGeneratedType`, content the user
//!   never copied (text expansions, app-generated writes)
//!
//! ZnonClip checks pasteboard **types only** before reading payload data, so
//! secret bytes are never pulled into memory or written to SQLite.

use log::info;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::NSString;

/// Marker set by password managers: do not keep this pasteboard content.
pub const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";

/// Marker for short-lived pasteboard content that should not be archived.
pub const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";

/// Marker for content an app wrote without the user copying anything.
pub const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

const CONCEALED_MARKERS: [&str; 2] = [CONCEALED_TYPE, "com.agilebits.onepassword"];
const TRANSIENT_MARKERS: [&str; 4] = [
    TRANSIENT_TYPE,
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
];
const AUTO_GENERATED_MARKERS: [&str; 1] = [AUTO_GENERATED_TYPE];

/// Which privacy markers were found on a pasteboard change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct PrivacyMarkers {
    pub concealed: bool,
    pub transient: bool,
    pub auto_generated: bool,
}

impl PrivacyMarkers {
    /// True if any marker is present (item must be skipped entirely).
    pub fn is_sensitive(self) -> bool {
        self.concealed || self.transient || self.auto_generated
    }

    /// Human-readable marker list for logs/UI (never includes secret content).
    pub fn describe(self) -> String {
        let mut parts = Vec::new();
        if self.concealed {
            parts.push("ConcealedType");
        }
        if self.transient {
            parts.push("TransientType");
        }
        if self.auto_generated {
            parts.push("AutoGeneratedType");
        }
        if parts.is_empty() {
            "none".to_string()
        } else {
            parts.join(" + ")
        }
    }

    fn note(&mut self, t: &str) {
        if CONCEALED_MARKERS.contains(&t) {
            self.concealed = true;
        } else if TRANSIENT_MARKERS.contains(&t) {
            self.transient = true;
        } else if AUTO_GENERATED_MARKERS.contains(&t) {
            self.auto_generated = true;
        }
    }
}

/// Inspect a list of pasteboard type UTI strings for privacy markers.
pub fn inspect_types(types: &[String]) -> PrivacyMarkers {
    let mut markers = PrivacyMarkers::default();
    for t in types {
        // Case-sensitive match: markers are exact strings per nspasteboard.org.
        markers.note(t);
    }
    markers
}

/// Returns `true` if the type list indicates sensitive content.
#[allow(dead_code)] // Public helper for tests and future callers
pub fn is_sensitive(types: &[String]) -> bool {
    inspect_types(types).is_sensitive()
}

/// Read available types from `NSPasteboard` without reading payload **contents**.
///
/// Only type UTIs are collected — never `stringForType` / `dataForType` for
/// the secret payload itself.
pub fn pasteboard_type_strings(pb: &NSPasteboard) -> Vec<String> {
    let Some(types) = pb.types() else {
        return Vec::new();
    };
    let mut out = Vec::with_capacity(types.count() as usize);
    for i in 0..types.count() {
        let t = types.objectAtIndex(i);
        // NSPasteboardType is NSString
        out.push(t.to_string());
    }
    out
}

/// Inspect the pasteboard for privacy markers (types only — no secret payload).
///
/// Uses both `types()` and `availableTypeFromArray:` (one marker at a time, as
/// it returns only the first match) so markers declared with empty data count.
pub fn inspect_pasteboard(pb: &NSPasteboard) -> PrivacyMarkers {
    let mut markers = inspect_types(&pasteboard_type_strings(pb));
    for marker in CONCEALED_MARKERS
        .iter()
        .chain(TRANSIENT_MARKERS.iter())
        .chain(AUTO_GENERATED_MARKERS.iter())
    {
        let ns = NSString::from_str(marker);
        let probe = objc2_foundation::NSArray::from_slice(&[&*ns]);
        if pb.availableTypeFromArray(&probe).is_some() {
            markers.note(marker);
        }
    }
    markers
}

/// Log that a clipboard change was skipped for privacy — **never** log content.
pub fn log_skipped(markers: PrivacyMarkers) {
    // Use info so it's visible with default RUST_LOG=info during manual testing.
    info!(
        "privacy: skipped clipboard change ({}) — content not stored",
        markers.describe()
    );
}

/// Short status-line text for the popover (no secret data).
pub fn status_message(markers: PrivacyMarkers) -> String {
    format!("Last copy skipped (privacy: {})", markers.describe())
}

/// Helper used by tests / future tooling: does this NSString type match a marker?
#[allow(dead_code)]
pub fn nsstring_is_marker(s: &NSString) -> bool {
    let t = s.to_string();
    let mut m = PrivacyMarkers::default();
    m.note(&t);
    m.is_sensitive()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_concealed() {
        let types = vec![
            "public.utf8-plain-text".into(),
            CONCEALED_TYPE.into(),
        ];
        let m = inspect_types(&types);
        assert!(m.concealed);
        assert!(!m.transient);
        assert!(m.is_sensitive());
        assert!(is_sensitive(&types));
    }

    #[test]
    fn detects_transient() {
        let types = vec![TRANSIENT_TYPE.into(), "public.utf8-plain-text".into()];
        let m = inspect_types(&types);
        assert!(!m.concealed);
        assert!(m.transient);
        assert!(m.is_sensitive());
    }

    #[test]
    fn detects_both() {
        let types = vec![
            CONCEALED_TYPE.into(),
            TRANSIENT_TYPE.into(),
            "public.utf8-plain-text".into(),
        ];
        let m = inspect_types(&types);
        assert!(m.concealed && m.transient && m.is_sensitive());
        assert_eq!(m.describe(), "ConcealedType + TransientType");
    }

    #[test]
    fn detects_auto_generated_and_legacy_markers() {
        let m = inspect_types(&[AUTO_GENERATED_TYPE.into(), "public.utf8-plain-text".into()]);
        assert!(m.auto_generated && m.is_sensitive());
        assert_eq!(m.describe(), "AutoGeneratedType");

        // 1Password's legacy marker counts as concealed.
        assert!(inspect_types(&["com.agilebits.onepassword".into()]).concealed);
        // Legacy transient markers from text expanders.
        for t in [
            "de.petermaurer.TransientPasteboardType",
            "com.typeit4me.clipping",
            "Pasteboard generator type",
        ] {
            assert!(inspect_types(&[t.into()]).transient, "{t}");
        }
        // org.nspasteboard.source is informational, never a reason to skip.
        assert!(!is_sensitive(&["org.nspasteboard.source".into()]));
        // Matching is exact: a lookalike is not a marker.
        assert!(!is_sensitive(&["org.nspasteboard.concealedtype".into()]));
    }

    #[test]
    fn normal_types_not_sensitive() {
        let types = vec![
            "public.utf8-plain-text".into(),
            "public.html".into(),
            "public.tiff".into(),
        ];
        assert!(!is_sensitive(&types));
        assert!(!inspect_types(&types).is_sensitive());
    }

    #[test]
    fn empty_types_not_sensitive() {
        assert!(!is_sensitive(&[]));
    }

    /// Writes a concealed payload to the real pasteboard and verifies detection.
    ///
    /// Ignored by default (mutates system clipboard). Run with:
    /// `cargo test privacy::tests::live_pasteboard_concealed -- --ignored --nocapture`
    #[test]
    #[ignore = "mutates system clipboard"]
    fn live_pasteboard_concealed() {
        use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
        use objc2_foundation::{NSArray, NSData, NSString};

        let pb = NSPasteboard::generalPasteboard();
        pb.clearContents();

        let plain = unsafe { NSPasteboardTypeString };
        let concealed = NSString::from_str(CONCEALED_TYPE);
        // NSPasteboardType is NSString — declare both plain text and the privacy marker.
        let types = NSArray::from_slice(&[plain, &*concealed]);
        // SAFETY: type array is valid NSPasteboardType strings; owner is None.
        let _ = unsafe { pb.declareTypes_owner(&types, None) };

        // Set the privacy marker *before* the secret so a concurrent poller never
        // sees plaintext without ConcealedType (password managers write atomically).
        let empty = NSData::with_bytes(&[]);
        assert!(pb.setData_forType(Some(&empty), &concealed));
        assert!(pb.setString_forType(&NSString::from_str("super-secret-password"), plain));

        let markers = inspect_pasteboard(&pb);
        assert!(
            markers.concealed,
            "expected ConcealedType on pasteboard, types={:?}",
            pasteboard_type_strings(&pb)
        );
        assert!(markers.is_sensitive());
        // Critical: we never assert on the secret string here — only markers.
    }

    /// Same as above for TransientType (Bitwarden-style).
    #[test]
    #[ignore = "mutates system clipboard"]
    fn live_pasteboard_transient() {
        use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
        use objc2_foundation::{NSArray, NSData, NSString};

        let pb = NSPasteboard::generalPasteboard();
        pb.clearContents();

        let plain = unsafe { NSPasteboardTypeString };
        let transient = NSString::from_str(TRANSIENT_TYPE);
        let types = NSArray::from_slice(&[plain, &*transient]);
        let _ = unsafe { pb.declareTypes_owner(&types, None) };
        // Marker first, then payload (same ordering rationale as ConcealedType test).
        assert!(pb.setData_forType(Some(&NSData::with_bytes(&[])), &transient));
        assert!(pb.setString_forType(&NSString::from_str("temp-secret"), plain));

        let markers = inspect_pasteboard(&pb);
        assert!(markers.transient && markers.is_sensitive());
    }
}
